
for (let i = 2; i <= 20; i += 2) {
    console.log(i);
}

console.log("The first 10 positive even numbers starting from 2 generated by using for loop");

let i = 2;
while (i <= 20) {
    console.log(i);
    i += 2;
}
console.log("The first 10 positive even numbers starting from 2 generated by using while loop");


i= 2;
do {
    console.log(i);
    i += 2;
} while (i <= 20);
console.log("GThe first 10 positive even numbers starting from 2 generated by using do-while loop");